### PR TITLE
42 bug failing test cases

### LINKED ISSUE #42: bug: failing test cases
There are 12 test cases failing in the repo.

Run the tests and rectify.

### PR DESCRIPTION
**Pull request by ryanwolhuter**
Fixes #42 

All tests are now passing.

Most of the failures were in the old tests that lived in the /test directory.

I have consolidated all of the tests into each repo's respective /src/test directory and was therefore able to remove the /test directory in the root of the project.

In some cases I simply copied the test files since there was no other file with the same name testing the same things.

In the cases where there were two test files with the same name, I went through the tests and unified them in the single file scoped to the individual document model's /src/test directory.

### CODE REVIEW

File: document-models/budget-statement/src/reducers/line-item.ts [hunk 1]
```diff
@@ -21,8 +21,8 @@ function isEqual(
     lineItem: LineItem
 ) {
     return (
-        lineItemInput.category === lineItem.category?.id &&
-        lineItemInput.group === lineItem.group?.id
+        lineItemInput.category === lineItem.category &&
```
Comment (ryanwolhuter) [inline document-models/budget-statement/src/reducers/line-item.ts:24]: I think this was a bug — the values we use in the tests never reference an `id` and treats the value as being the string itself. I'll add another comment by the test code I'm referring to.

File: document-models/budget-statement/src/tests/scenario.test.ts [hunk 2]
```diff
@@ -0,0 +1,82 @@
+/* eslint-disable @typescript-eslint/no-unsafe-call */
```
Comment (ryanwolhuter) [inline document-models/budget-statement/src/tests/scenario.test.ts:1]: commented out because the `document-model-specs` dir no longer exists and trying to scan for the dir breaks the code

File: document-models/budget-statement/src/reducers/line-item.ts (hunk 1 above)
Comment (acaldas) [reply document-models/budget-statement/src/reducers/line-item.ts:24]: From what I remember `group` and `category` can either be an Id or a an object with `{id, name, ...}`.
If we need to actually use budget statements in the future we'll worry about it then.

**Review by acaldas — APPROVED** [review]
