### PR TITLE
Fixes document model initial state validation

### LINKED ISSUE #5: Fix GraphQL codegen on Document Model Editor story

### PR DESCRIPTION
**Pull request by acaldas**
Also fixes #5 

Screenshot 2023-11-17 at 12 11 35

### CODE REVIEW

File: editors/document-model/editor-schema.tsx [hunk 1]
```diff
@@ -127,16 +104,16 @@ export default function EditorSchema({
...
             if (value) {
-                generateSchema(value);
+                generateSchema(value, name);
             } else {
                 // TODO clear current schema?
             }
         });
-    }, [editorRef.current]);
+        return listener.dispose;
+    }, [editorRef.current, name]);
```
Comment (ryanwolhuter) [inline editors/document-model/editor-schema.tsx:116]: You probably don't want to have `editorRef.current` in this dependency array

https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/

**Review by ryanwolhuter — APPROVED** [review]
LGTM 💪 

one small comment below
